name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: native
    if: >-
      github.event_name == 'pull_request'
      && !contains(github.event.pull_request.title || '', '[ci-skip]')
    steps:
      - uses: actions/checkout@v4
      - name: "check"
        run: nix flake check

  build:
    runs-on: native
    needs: [check]
    strategy:
      matrix:
        host: [ishtar, athena]
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: nixos-rebuild build --flake .#${{ matrix.host }} --no-link

  dry-activate:
    runs-on: native
    needs: [build]
    strategy:
      matrix:
        host: [ishtar, athena]
    steps:
      - uses: actions/checkout@v4
      - name: "dry-activate"
        run: nixos-rebuild dry-activate --flake .#${{ matrix.host }} --target-host nixbldRemote@${{ matrix.host }}.ts --sudo

  deploy:
    runs-on: native
    strategy:
      matrix:
        host: [ishtar, athena]
    if: >-
      github.event_name == 'push'
      && !contains(github.event.head_commit.message || '', '[ci-skip]')
    steps:
      - uses: actions/checkout@v4
      - name: "deploy"
        run: nixos-rebuild switch --flake .#${{ matrix.host }} --target-host nixbldRemote@${{ matrix.host }}.ts --sudo
