{ self, ... }: {
  flake.nixosModules.forgejo =
    {
      config,
      pkgs,
      ...
    }:
    let
      inherit (self.myLib.constants) fqdn;
      inherit (self.myLib.helpers) roleHost;
      inherit (self.myLib.directory.hosts.${config.networking.hostName}.ip) internal;
      mailRelay =
        (roleHost [
          "edge"
          "mail"
        ]).ip.internal;
    in
    {
      users.groups.git = { };
      users.users.git = {
        isSystemUser = true;
        group = "git";
        home = "/var/lib/forgejo";
        shell = "${pkgs.bash}/bin/bash";
      };

      # git is a static user, so the persist entry must carry its owner - a plain
      # string lands root:root and forgejo can't write its own state. inert on
      # non-impermanent hosts. (/var/backup/forgejo is regenerated by the dump
      # preHook each borg run, so it doesn't need persisting.)
      environment.persistence."/persist".directories = [
        {
          directory = "/var/lib/forgejo";
          user = "git";
          group = "git";
          mode = "0700";
        }
      ];

      # I've shamelessly stolen catppuccin's config for their themes here
      systemd.tmpfiles.settings."10-catppuccin-forgejo-theme" =
        let
          cfg = config.services.forgejo;
          inherit (cfg) customDir;
        in
        {
          "${customDir}/public/assets/css"."C+" = {
            argument = toString pkgs.forgejo-themes;
          };
          "${customDir}/public/assets".d = { inherit (cfg) user group; };
          "${customDir}/public".d = { inherit (cfg) user group; };
        };
      services = {
        borgbackup.jobs.${config.networking.hostName} = {
          preHook = "systemctl start forgejo-dump.service";
          paths = [ config.services.forgejo.dump.backupDir ];
        };

        forgejo = {
          enable = true;
          user = "git";
          dump = {
            enable = true;
            backupDir = "/var/backup/forgejo";
            type = "tar";
            file = "forgejo-dump";
          };
          settings = {
            DEFAULT = {
              APP_NAME = "git";
              APP_SLOGAN = "just the code";
            };
            repository = {
              PREFERED_LICENSES = "MIT";
              USE_COMPAT_SSH_URI = false;
              GO_GET_CLONE_URL_PROTOCOL = "ssh";
              ENABLE_PUSH_CREATE_USER = true;
              DISABLE_STARS = true;
              DISABLE_FORKS = true;
            };
            ui =
              let
                theme = "catppuccin-mocha-mauve";
              in
              {
                DEFAULT_THEME = theme;
                THEMES = theme;
              };
            "ui.meta" = {
              AUTHOR = "Sarah Lament";
              DESCRIPTION = "just the code";
            };
            server = {
              DOMAIN = "git.${fqdn}";
              ROOT_URL = "https://git.${fqdn}";
              LANDING_PAGE = "/sarahlament";
              HTTP_PORT = self.myLib.directory.services.git.port;
              HTTP_ADDR = internal;

              SSH_DOMAIN = "${config.networking.hostName}.${fqdn}";
              SSH_USER = "git";
              SSH_PORT = 22;
              START_SSH_SERVER = false;
              SSH_CREATE_AUTHORIZED_KEYS_FILE = true;
            };
            service = {
              DISABLE_REGISTRATION = true;
              REQUIRE_SIGNIN_TO_VIEW = false;
            };
            mailer = {
              ENABLED = true;
              # relay unauthenticated over WireGuard to the mailserver's internal
              # address (trusted via mynetworks); "smtp" is plaintext, no TLS,
              # since the tunnel already encrypts
              PROTOCOL = "smtp";
              SMTP_ADDR = mailRelay;
              SMTP_PORT = 25;
              FROM = "git@${fqdn}";
            };
            actions.ENABLED = true;
          };
        };
      };
    };
}
