vaultwardenToken: ENC[AES256_GCM,data:PP6RfszA/4AGNBp/fRGqhsfnQnmLv9cq6FB5JbkPtS72H6tknl6tbdSsbNuspkXoB4nb+YuMbctnffJVd5HjEQXTwdWUisZ9xIwA,iv:kZXM2SEyWriD37WUvdoJeqLF1qC4UbnHFacyjp9M2d8=,tag:l68zS/VvH4+nQUYcMGXTIw==,type:str]
forgejoRunnerToken: ENC[AES256_GCM,data:U1GL+W49LhvYDJww8kGyMueCb91NojEj66aWGnd8ndpwzsqHKBwcIA==,iv:GHRpLhd8Pd7khysdvlDCxg3XVTZ5TTtZQzYtgbVCSb0=,tag:+bWlYLgGSB+mZzh3Uk8+Tw==,type:str]
grafanaSecretKey: ENC[AES256_GCM,data:OPI/WZYzAO7jy0AdTr268lk0Wg==,iv:aLokznuTTw5DNs5MWBf1Bh0Z/pO3wtzWjX01ivXBDrE=,tag:U0z7jznqdNmPW9MbyQwuaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIenVvbXJ0UEE3ZEVySmQw
            Q0dOQ0pnZ3hzQ1RIYmpKTnpDd0UvS1FuY2hFClVsZUswSWEzVEhlWEZCQVZDdm1h
            d2dublpsUVNibDlTc1lrQ2dPK3NDRVkKLS0tIEc5Sm1maWpnUHBCUjhsZmFzVFlO
            R2JwbFhUZ0JCRVdWL2xyY3V3VWdGeXMKTZHYntTpjOJK6Vr3mbtpgsNqV3sIzvJx
            BvX+MLnLA5nrYPH0TY8XlCmoGhxr87biLYBUCP8ak5X1/+TAQcBHYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15k8clh8j26kxmnrfaa4a83s7mm7d5xl7vueh04kkrtpc2shhcuzqewurla
    lastmodified: "2026-07-03T06:12:21Z"
    mac: ENC[AES256_GCM,data:plp8uJLLT3HwzvUvhP4tuwhTTgpfLgn7Y5XnU3jSDLGJJNYtXDW2NKmZyYM/rfmzrFpaU8BsMePwAd2P1pFvgcknURxd2zPewdtvTeXITwicAzy+kfC/KEWu0VLFGrXtBEFsfQ7XAaNyJccVALtLsJrEj8WuxT7YO1BYEwCH4yk=,iv:KPe8huLFohUieOOooLnoDVmcyJsy7CxSFpRHoy0TLm8=,tag:q8RTMCLG0Ddy6D8Skr/t8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
